import "./globals.css";
import type { Metadata } from "next";
import { Dosis, Laila, Mulish } from "next/font/google";
import { ThemeProvider } from "../../providers/ThemeProvider";
import { useLocale } from "next-intl";
import { notFound } from "next/navigation";
import { locales } from "@/navigation";
import { unstable_setRequestLocale } from "next-intl/server";

const dosis = Dosis({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-dosis",
});

const laila = Laila({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-laila",
});

const mulish = Mulish({
  subsets: ["latin"],
  weight: ["300"],
  variable: "--font-mulish",
});

export const metadata: Metadata = {
  title: "A.Malecki Portfolio",
  description: "Generated by create next app",
};
type Props = {
  children: React.ReactNode;
  params: { locale: string };
};

export default function RootLayout({ children, params: { locale } }: Props) {
  // Validate that the incoming `locale` parameter is valid
  if (!locales.includes(locale as any)) notFound();

  // Enable static rendering
  unstable_setRequestLocale(locale);

  return (
    <html lang={locale} className="dark">
      <body
        className={`${mulish.variable} ${laila.variable} ${dosis.variable}`}
      >
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
